# Generated by Django 5.2.9 on 2026-03-03 19:21

import django.db.models.deletion
import prime_crm.utils
from django.db import migrations, models


DEFAULT_STAGES = [
    ('new', 1),
    ('contacted', 2),
    ('negotiation', 3),
    ('qualified', 4),
    ('lost', 5),
]


def seed_default_stages(apps, schema_editor):
    LeadStage = apps.get_model('leads', 'LeadStage')
    for name, order in DEFAULT_STAGES:
        LeadStage.objects.get_or_create(
            name=name,
            defaults={'order': order, 'is_default': True},
        )


def remove_default_stages(apps, schema_editor):
    LeadStage = apps.get_model('leads', 'LeadStage')
    LeadStage.objects.filter(
        name__in=[name for name, _ in DEFAULT_STAGES],
        is_default=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_form_id_lead_max_budget_lead_min_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.UUIDField(default=prime_crm.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (ascending).')),
                ('is_default', models.BooleanField(default=False, help_text='True for the built-in default stages.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RunPython(seed_default_stages, remove_default_stages),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_leads', to='leads.leadstage'),
        ),
    ]
