# Generated by Django 5.2.9 on 2026-03-05 20:14

import django.db.models.deletion
import prime_crm.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=prime_crm.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
