# Generated by Django 5.2.9 on 2026-03-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_leadnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
    ]
