# Generated by Django 5.2.9 on 2026-03-05 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_remove_lead_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadnote',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead'),
        ),
    ]
