# Generated by Django 5.2.9 on 2026-03-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_leadtransfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='next_follow_up',
        ),
        migrations.AddField(
            model_name='leadnote',
            name='next_follow_up',
            field=models.DateField(blank=True, null=True),
        ),
    ]
