# Generated by Django 5.2.9 on 2026-03-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_remove_lead_next_follow_up_leadnote_next_follow_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadnote',
            name='next_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
