# Generated by Django 5.2.9 on 2026-03-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_assigned_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadnote',
            name='leadnote_lead_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadnote',
            name='leadnote_follow_up_idx',
        ),
    ]
