# Generated by Django 5.2.9 on 2026-03-30 11:58

from django.db import migrations, models


def set_stage_types(apps, schema_editor):
    LeadStage = apps.get_model('leads', 'LeadStage')
    # Qualified
    LeadStage.objects.filter(name__iexact='won').update(stage_type='qualified')
    LeadStage.objects.filter(name__iexact='qualified').update(stage_type='qualified')
    # Unqualified
    LeadStage.objects.filter(name__iexact='lost').update(stage_type='unqualified')
    LeadStage.objects.filter(name__iexact='unqualified').update(stage_type='unqualified')

def reverse_stage_types(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_remove_lead_lead_assigned_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstage',
            name='stage_type',
            field=models.CharField(choices=[('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('default', 'Default')], default='default', help_text='Semantic type of the stage — independent of the display name.', max_length=20),
        ),
        migrations.RunPython(set_stage_types, reverse_stage_types),
    ]
