# Generated by Django 5.2.9 on 2026-03-03 05:43

import prime_crm.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=prime_crm.utils.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('type', models.CharField(choices=[('plot', 'Plot'), ('apartment', 'Apartment'), ('house', 'House'), ('portion', 'Portion'), ('office', 'Office')], default='plot', max_length=20)),
                ('form_id', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_unit', models.CharField(choices=[('marla', 'Marla'), ('sqft', 'Sqft')], default='marla', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
