# Generated by Django 5.2.9 on 2026-03-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('plot', 'Plot'), ('apartment', 'Apartment'), ('house', 'House'), ('portion', 'Portion'), ('office', 'Office'), ('townhouse', 'Townhouse')], default='plot', max_length=20),
        ),
    ]
