# Generated by Django 5.2.9 on 2026-03-02 07:22

import authentication.models.invite
import authentication.models.otp
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=authentication.models.invite.default_expires_at),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.UUIDField(default=core.utils.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='expires_at',
            field=models.DateTimeField(default=authentication.models.otp.default_otp_expires_at),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='id',
            field=models.UUIDField(default=core.utils.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
